before_script:
    - date
    - uname -p
    - uname -s
    - printenv | sort

gcc:
    image: gpdowning/gcc
    script:
    - cat Makefile
    - make versions
    - ls -al
    - make test
    - ls -al
    - make ../cs371p-voting-tests
    - ls -al ../cs371p-voting-tests/
    - ls -al
    - make run
    - ls -al
    # - make run-all //put back when testing public repo
    - ls -al
    - make check
    - ls -al
